DVDShop/DVDShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('store/', include('storedvd.urls')),
    path('', RedirectView.as_view(url='/store/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DVDShop/storedvd/urls.py
from django.urls import path

from .views import index, delivery, contacts, section, ProductDetailView

app_name = 'storedvd'
urlpatterns = [
    path('', index, name='index'),
    path('delivery', delivery, name='delivery'),
    path('contacts', contacts, name='contacts'),
    path('section/<int:id>/', section, name='section'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
]

DVDShop/storedvd/models.py
import datetime

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse


class Section(models.Model):
    title = models.CharField(
        max_length=70,
        help_text='Название раздела',
        unique=True,
        verbose_name='Раздел',
    )

    class Meta:
        ordering = ['id']
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'

    def get_absolute_url(self):
        return reverse('storedvd:section', args=[self.id])

    def __str__(self):
        return self.title


class Product(models.Model):
    section = models.ForeignKey(
        Section,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Раздел',
    )
    title = models.CharField(
        max_length=70,
        verbose_name='Название',
    )
    image = models.ImageField(
        upload_to='images',
        verbose_name='Изображение',
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Цена',
    )
    year = models.SmallIntegerField(
        validators=[
            MinValueValidator(1900),
            MaxValueValidator(datetime.date.today().year)
        ],
        verbose_name='Год',
    )
    country = models.CharField(
        max_length=70,
        verbose_name='Страна',
    )
    director = models.CharField(
        max_length=70,
        verbose_name='Режиссер',
    )
    play = models.SmallIntegerField(
        help_text='В секундах',
        null=True,
        blank=True,
        verbose_name='Продолжительность',
        validators=[MinValueValidator(1)],
    )
    casts = models.TextField(
        verbose_name='В ролях',
    )
    description = models.TextField(
        verbose_name='Описание',
    )
    date = models.DateField(
        auto_now_add=True,
        verbose_name='Дата добавления',
    )

    class Meta:
        ordering = ['title', 'year']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'{self.title} ({self.section.title})'


class Discount(models.Model):
    code = models.CharField(
        max_length=10,
        verbose_name='Код скидки',
    )
    value = models.SmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(100)],
        verbose_name='Размер скидки',
        help_text='В процентах',
    )

    class Meta:
        ordering = ['-value']
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'

    def __str__(self):
        return f'{self.code} ({self.value}%)'


class Order(models.Model):
    need_delivery = models.BooleanField(
        verbose_name='Необходима доставка',
    )
    discount = models.ForeignKey(
        Discount,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Скидка',
    )
    name = models.CharField(
        max_length=70,
        verbose_name='Имя',
    )
    phone = models.CharField(
        max_length=20,
        verbose_name='Телефон',
    )
    email = models.EmailField()
    address = models.TextField(
        blank=True,
        verbose_name='Адрес',
    )
    notice = models.CharField(
        max_length=128,
        blank=True,
        verbose_name='Примечание',
    )
    date_order = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата заказа',
    )
    date_send = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name='Дата отправки',
    )
    STATUSES = [
        ('NEW', 'Новый заказ'),
        ('APR', 'Подтвержден'),
        ('PAY', 'Оплачен'),
        ('CNL', 'Отменён'),
    ]
    status = models.CharField(
        choices=STATUSES,
        max_length=3,
        default='NEW',
        verbose_name='Статус',
    )

    class Meta:
        ordering = ['-date_order']
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'ID: {self.pk}'


class OrderLine(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        verbose_name='Заказ',
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Товар',
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0.00,
        verbose_name='Цена',
    )
    count = models.SmallIntegerField(
        validators=[MinValueValidator(1)],
        default=1,
        verbose_name='Количество',
    )

    class Meta:
        verbose_name = 'Строка заказа'
        verbose_name_plural = 'Строки заказа'

    def __str__(self):
        return f'Заказ (ID:{self.order.id}) {self.product.title} {self.count}'

DVDShop/storedvd/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView

from .models import Product, Section


def sorted_title_or_price(request):
    order_by = '-date'
    if all([request.GET.__contains__('sort'), request.GET.__contains__('up')]):
        if all([
            any([request.GET['sort'] == 'title', request.GET['sort'] == 'price']),
            any([request.GET['up'] == '0', request.GET['up'] == '1']),
        ]):
            order_by = f'{"" if request.GET["up"] == "1" else "-"}{request.GET["sort"]}'
    return order_by


def index(request):
    products = Product.objects.order_by(sorted_title_or_price(request)).all()[:8]
    context = {
        'products': products,
    }
    return render(request, 'index.html', context=context)


def delivery(request):
    return render(request, 'delivery.html')


def contacts(request):
    return render(request, 'contacts.html')


def section(request, id):
    obj = get_object_or_404(Section, pk=id)
    products = Product.objects.filter(section__exact=obj).order_by(
        sorted_title_or_price(request)
    )
    context = {
        'section': obj,
        'products': products,
    }
    return render(request, 'section.html', context=context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = Product.objects.filter(
            section__exact=self.get_object().section
        ).order_by('?').exclude(id=self.get_object().id)[:4]
        return context

DVDShop/storedvd/templates/contacts.html
{% extends 'main.html' %}
{% block description %}<meta name="description" content="Контакты Интернет-магазина" />{% endblock %}
{% block keywords %}
    <meta name="keywords" content="интернет магазин, интернет магазин dvd, интернет магазин dvd диски, контакты" />
{% endblock %}
{% block title %}Контакты{% endblock %}
{% block content %}
    <div id="article">
        <h2>Контакты</h2>
        <p>Мы находимся по адресу г. Москва, ул. такая-то, д. такой-то.</p>
        <p>Мы работаем с 09:00 до 21:00 без перерыва и выходных.</p>
    </div>
    <div id="map" style="width:95%; height:300px">
        <script src="//api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU" type="text/javascript"></script>
        <script src="https://yandex.st/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            ymaps.ready(init);

            function init () {
                var myMap = new ymaps.Map("map", {
                        center: [55.739533,37.624744],
                        zoom: 17
                    }),
                    myPlacemark = new ymaps.Placemark([55.739533,37.624744], {
                        // Чтобы балун и хинт открывались на метке, необходимо задать ей определенные свойства.
                        balloonContentHeader: "Наш магазин",
                        balloonContentBody: "<em>г. Москва, ул. такая-то, д. такой-то</em>",
                        balloonContentFooter: "Ждём Вас!",
                        hintContent: "Мы здесь!"
                    });
                // элемента управления и его параметры.
                myMap.controls
                    // Кнопка изменения масштаба.
                    .add('zoomControl', { left: 5, top: 5 })
                    // Список типов карты
                    .add('typeSelector')
                    // Кнопка изменения масштаба - компактный вариант.
                    // Расположим её справа.
                    .add('smallZoomControl', { right: 5, top: 75 })
                    // Стандартный набор кнопок
                    .add('mapTools', { left: 35, top: 5 });
                myMap.geoObjects.add(myPlacemark);

                // Показываем хинт на карте (без привязки к геообъекту).
                myMap.hint.show(myMap.getCenter(), "Содержимое хинта", {
                    // Опция: задержка перед открытием.
                    showTimeout: 1500
                });
            }
        </script>
    </div>
{% endblock %}

DVDShop/storedvd/templates/delivery.html
{% extends 'main.html' %}
{% block description %}<meta name="description" content="Оплата и доставка в Интернет-магазине" />{% endblock %}
{% block keywords %}
    <meta name="keywords" content="интернет магазин, интернет магазин dvd, интернет магазин dvd диски, оплата, доставка" />
{% endblock %}
{% block title %}Оплата и доставка{% endblock %}
{% block content %}
    <div id="article">
        <h2>Оплата и доставка</h2>
        <p>У нас есть 2 варианта доставки: доставка по почте наложенным платежом и самовывоз.</p>
        <p>Возможны и другие варианты оплаты и доставки, о которых можно договориться по телефону с менеджером после оформление заказа.</p>
    </div>
{% endblock %}

DVDShop/storedvd/templates/index.html
{% extends 'main.html' %}

{% block title %}DVD Store{% endblock %}
{% block content %}
    <table>
        <tr>
            <td rowspan="2">
                <div class="header">
                    {% block header %}<h3>Каталог</h3>{% endblock %}
                </div>
            </td>
            <td class="section_bg"></td>
            <td class="section_right"></td>
        </tr>
        <tr>
            <td colspan="2">
                <table class="sort">
                    <tr>
                        <td>Сортировать по:</td>
                        <td>цене (<a href="{{ request.path }}?sort=price&amp;up=1">возр.</a> | <a href="{{ request.path }}?sort=price&amp;up=0">убыв.</a>)</td>
                        <td>названию (<a href="{{ request.path }}?sort=title&amp;up=1">возр.</a> | <a href="{{ request.path }}?sort=title&amp;up=0">убыв.</a>)</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <table class="products">
        {% for product in products %}
            {% cycle '<tr>' '' '' '' %}
                {% include 'product.html' %}
            {% if forloop.last %}
                </tr>
            {% else %}
                {% cycle '' '' '' '</tr>' %}
            {% endif %}
        {% endfor %}
    </table>
{% endblock %}

DVDShop/storedvd/templates/main.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru">
<head>
	<title>{% block title %}{{ title }}{% endblock %}</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	{% block description %}<meta name="description" content="Интернет-магазин по продаже DVD-дисков." />{% endblock %}
	{% block keywords %}
		<meta name="keywords" content="интернет магазин, интернет магазин dvd, интернет магазин dvd диски" />
	{% endblock %}
	{% load static %}
	<link rel="stylesheet" href="{% static 'styles/main.css' %}" type="text/css" />
	<script type="text/javascript" src="{% static 'js/functions.js' %}"></script>
	<link href="{% static 'favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />
</head>
<body>
	<div id="container">
		<div id="header">
			<img src="{% static 'images/header.png' %}" alt="Шапка" />
			<div>
				<p class="red">8-800-123-45-67</p>
				<p class="blue">Время работы с 09:00 до 21:00<br />без перерыва и выходных</p>
			</div>
			<div class="cart">
				<p class="cart_title">Корзина</p>
				<p class="blue">Текущий заказ</p>
				<p>В корзине <span>0</span> товаров<br />на сумму <span>0</span> руб.</p>
				<a href="#">Перейти в корзину</a>
			</div>
		</div>
		<div id="topmenu">
			<ul>
				<li>
					<a href="{% url 'storedvd:index' %}">ГЛАВНАЯ</a>
				</li>
				<li>
					<img src="{% static 'images/topmenu_border.png' %}" alt="" />
				</li>
				<li>
					<a href="{% url 'storedvd:delivery' %}">ОПЛАТА И ДОСТАВКА</a>
				</li>
				<li>
					<img src="{% static 'images/topmenu_border.png' %}" alt="" />
				</li>
				<li>
					<a href="{% url 'storedvd:contacts' %}">КОНТАКТЫ</a>
				</li>
			</ul>
			<div id="search">
				<form name="search" action="https://storedvd.ru/search" method="get">
					<table>
						<tr>
							<td class="input_left"></td>
							<td>
								<input type="text" name="q" value="поиск" onfocus="if(this.value == 'поиск') this.value=''" onblur="if(this.value == '') this.value='поиск'" />
							</td>
							<td class="input_right"></td>
						</tr>
					</table>
				</form>
			</div>
		</div>
		<div id="content">
			<div id="left">
				<div id="menu">
					<div class="header">
						<h3>Разделы</h3>
					</div>
					<div id="items">
						{% for section in sections %}
						<p><a href="{{ section.get_absolute_url }}">{{ section }}</a></p>
						{% endfor %}
					</div>
					<div class="bottom"></div>
				</div>
			</div>
			<div id="right">
				{% block content %}
				{% endblock %}
			</div>
			<div class="clear"></div>
			<div id="footer">
				<div id="pm">
					<table>
						<tr>
							<td>Способы оплаты:</td>
							<td>
								<img src="{% static 'images/pm.png' %}" alt="Способы оплаты" />
							</td>
						</tr>
					</table>
				</div>
				<div id="copy">
					<p>Copyright &copy; Site.ru. Все права защищены.</p>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

DVDShop/storedvd/templates/product.html
<td>
    <div class="intro_product">
        <p class="img">
            <img src="{{ MEDIA_URL }}{{ product.image.url }}" alt="{{ product.title }}">
        </p>
        <p class="title">
            <a href="{% url 'storedvd:product' product.id %}">{{ product.title }}</a>
        </p>
        <p class="price">
            {{ product.price }}
        </p>
        <p>
            <a class="link_cart" href="#"></a>
        </p>
    </div>
</td>

DVDShop/storedvd/templates/product_detail.html
{% extends 'main.html' %}
{% block description %}<meta name="description" content="{{ product.title }} Интернет-магазин" />{% endblock %}
{% block keywords %}
    <meta name="keywords" content="интернет магазин, интернет магазин dvd, интернет магазин dvd диски, {{ product.title }}" />
{% endblock %}
{% block title %}{{ product.title }}{% endblock %}
{% block content %}
    <table id="hornav">
        <tr>
            {% load static %}
            <td>
                <a href="{% url 'storedvd:index' %}">Главная</a>
            </td>
            <td>
                <img src="{% static 'images/hornav_arrow.png' %}" alt="">
            </td>
            <td>
                <a href="{{ product.section.get_absolute_url }}">{{ product.section.title }}</a>
            </td>
            <td>
                <img src="{% static 'images/hornav_arrow.png' %}" alt="">
            </td>
            <td>
                {{ product.title }}
            </td>
        </tr>
    </table>
    <table id="product">
        <tr>
            <td class="product_img">
                <img src="{{ product.image.url }}" alt="{{ product.title }}">
            </td>
            <td class="product_desc">
                <p>Название: <span class="title">{{ product.title }}</span></p>
                <p>Год выхода: <span class="title">{{ product.year }}</span></p>
                <p>Жанр: <span class="title">{{ product.section.title }}</span></p>
                <p>Страна-производитель: <span class="title">{{ product.country }}</span></p>
                <p>Режиссёр: <span class="title">{{ product.director }}</span></p>
                <p>Продолжительность: <span class="title">{{ product.play }}</span></p>
                <p>В ролях: <span class="title">{{ product.casts }}</span></p>
                <table>
                    <tr>
                        <td>
                            <p class="price">{{ product.price }}</p>
                        </td>
                        <td>
                            <p>
                                <a class="link_cart" href="#"></a>
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <p class="desc_title">Описание:</p>
                <p class="desc">{{ product.description|linebreaksbr }}</p>
            </td>
        </tr>
    </table>
    <div id="others">
        <h3>С этим товаром часто заказывают:</h3>
        <table class="products">
            <tr>
                {% for other_product in products %}
                    {% include 'product.html' with product=other_product %}
                {% endfor %}
            </tr>
        </table>
    </div>
{% endblock %}

DVDShop/storedvd/templates/section.html
{% extends 'index.html' %}
{% block title %}{{ section.title }}{% endblock %}
{% block description %}<meta name="description" content="Раздел {{ section.title }} Интернет-магазина" />{% endblock %}
{% block keywords %}
    <meta name="keywords" content="интернет магазин, интернет магазин dvd, интернет магазин dvd диски, {{ section.title|lower }}" />
{% endblock %}
{% block header %}<h3>{{ section.title }}</h3>{% endblock %}